### ISSUE TITLE
The libmediapipe_jni.so file in mediapipe_android.arr is large

### ISSUE THREAD

**Issue by lvxixi4ever** [homuler/MediaPipeUnityPlugin#1237]
### Plugin Version or Commit ID

v0.14.3

### Unity Version

2022.3.27f1c1

### Your Host OS

Windows 10

### Target Platform

UnityEditor, Android

### Description

Hi! I noticed that in the MediaPipeUnityPlugin-all.zip file, the libmediapipe_jni.so in the mediapipe_android.arr is about 500MB, while the libmediapipe_jni.so in the mediapipe_android.arr generated after importing MediaPipeUnity.0.14.4.unitypackage is only about 20MB. What is the reason for this difference?

I used your workflow to generate four files: package-for-development-src-all, package-for-development-tarball, package-for-production-src-all, and package-for-production-tarball. What is the difference between these four files? I used the package-for-development-src-all file, and the libmediapipe_jni.so is also about 500MB. How can I compress the size of this file? Thanks!

**Comment by homuler** [comment]
Please download `MediaPipeUnityPlugin-all-stripped.zip` instead.
The debug symbols of the libraries in the file are stripped.

**Comment by lvxixi4ever** [comment]
> Please download `MediaPipeUnityPlugin-all-stripped.zip` instead. The symbols (e.g. the names of functions) of the libraries in the file are stripped.

Hi! In order to get MediaPipeUnityPlugin-all-stripped.zip (I updated some content and need to rebuild the library, so I can't directly download your MediaPipeUnityPlugin-all-stripped.zip.), I forked your project to my GitHub and used the workflow. However, I encountered an error during the linux-build stage:

System.IO.IOException: No space left on device : '/home/runner/runners/2.317.0/_diag/Worker_20240810-013608-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
Unhandled exception. System.IO.IOException: No space left on device : '/home/runner/runners/2.317.0/_diag/Worker_20240810-013608-utc.log'
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
System.IO.IOException: No space left on device : '/home/runner/runners/2.317.0/_diag/Worker_20240810-013608-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Common.Tracing.Error(Exception exception)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at System.Diagnostics.TraceSource.Flush()
   at GitHub.Runner.Common.TraceManager.Dispose(Boolean disposing)
   at GitHub.Runner.Common.TraceManager.Dispose()
   at GitHub.Runner.Common.HostContext.Dispose(Boolean disposing)
   at GitHub.Runner.Common.HostContext.Dispose()
   at GitHub.Runner.Worker.Program.Main(String[] args)

What is the reason for this? It seems the error indicates insufficient storage space. I tried to follow your steps to remove redundant logs by running the run-tests.yml file, but I encountered the following error:

ls: cannot access 'Unity_*.ulf': No such file or directory
Unity Editor version:    2021.3.33f1 (ee5a2aa03ab2)
Branch:                  2021.3/staging
Build type:              Release
Batch mode:              YES
System name:             Linux
Distro version:          #26~22.04.1-Ubuntu SMP Thu Jul 11 22:33:04 UTC 2024
Kernel version:          6.5.0-1025-azure
Architecture:            x86_64
Available memory:        15981 MB
[Licensing::Module] Trying to connect to existing licensing client channel...
[Licensing::IpcConnector] Connection attempt to the License Client on channel: "LicenseClient-runner" failed because channel doesn't exist; code: "0x80000002"
[Licensing::Module] Successfully launched the LicensingClient (PId: 1995)
[Licensing::IpcConnector] Successfully connected to the License Client on channel: "LicenseClient-runner" at "2024-08-10T01:30:36.190168Z"
[SignatureVerifier] Application signature verification not supported on this platform.
[Licensing::Client] Handshaking with LicensingClient:
  Version:                 1.13.1+ca5f299
  Session Id:              1239bc23957e409c819673bf6d0840ec
  Correlation Id:          36521fa2ef9443d457ba7428fd0fc896
  External correlation Id: 8387826288719182354
  Machine Id:              yn4XUhYJQVisjlp/q9ZhY781gA4=
[Licensing::Module] Successfully connected to LicensingClient on channel: "LicenseClient-runner" (connect: 0.45s, validation: 0.10s, handshake: 0.00s)
[Licensing::IpcConnector] Successfully connected to the License Notification on channel: "LicenseClient-runner-notifications" at "2024-08-10T01:30:36.290816Z"
[Licensing::Module] Connected to LicensingClient (PId: 1995, launch time: 0.00, total connection time: 0.55s)
Entitlement-based licensing initiated
[Licensing::Module] Error: Access token is unavailable; failed to update
[Licensing::Client] Error: Code 500 while processing request (status: Unable to update licenses. Errors: No ULF license found.,Token not found in cache)
[Licensing::Client] Error: Code 500 while updating license in client (status: Unable to update licenses. Errors: No ULF license found.,Token not found in cache)
[Licensing::Module] Error: "manualLicenseFile" must be provided with the path to a valid, non-empty, ULF file
Checking for leaked weakptr:
  Found no leaked weakptrs.
Memory Statistics:
[ALLOC_TEMP_TLS] TLS Allocator
  StackAllocators : 
    [ALLOC_TEMP_CurlRequest]
      Initial Block Size 64.0 KB
      Current Block Size 64.0 KB
      Peak Allocated Bytes 0 B
      Overflow Count 0
    [ALLOC_TEMP_CoreBusinessMetricsCache]
      Initial Block Size 64.0 KB
      Current Block Size 64.0 KB
      Peak Allocated Bytes 0 B
      Overflow Count 0
    [ALLOC_TEMP_Profiler.Dispatcher]
      Initial Block Size 64.0 KB
      Current Block Size 64.0 KB
      Peak Allocated Bytes 0 B
      Overflow Count 0
    [ALLOC_TEMP_AssetGarbageCollectorHelper] x 3
      Initial Block Size 64.0 KB
      Current Block Size 64.0 KB
      Peak Allocated Bytes 0 B
      Overflow Count 0
[ALLOC_MEMORYPROFILER]
  Requested Block Size 1.0 MB
  Peak Block count 1
  Peak Allocated memory 4.0 KB
  Peak Large allocation bytes 0 B
##utp:{"type":"MemoryLeaks","version":2,"phase":"Immediate","time":1723253436340,"processId":1989,"allocatedMemory":87607,"memoryLabels":[{"Default":530},{"Thread":64},{"Manager":6842},{"Serialization":40},{"BaseObject":12256},{"String":5203},{"HashMap":3668},{"Utility":1024},{"Curl":1112},{"PoolAlloc":120},{"GI":3248},{"VR":80},{"RestService":1022},{"License":3608},{"UnityConnect":28528},{"Collab":25},{"LocalIPC":216},{"ProfilerEditor":20021}]}
rm: cannot remove 'Unity_*.ulf': No such file or directory

It seems that the Unity_*.ulf file could not be found. What should I do?

**Comment by homuler** [comment]
> However, I encountered an error during the linux-build stage:

Thank you for reporting the issue. It is fixed by https://github.com/homuler/MediaPipeUnityPlugin/pull/1239.

**Comment by lvxixi4ever** [comment]
> > However, I encountered an error during the linux-build stage:
> 
> Thank you for reporting the issue. It is fixed by #1239.

Hi! When running the Release Packages workflow, I still get the following error:

System.IO.IOException: No space left on device : '/home/runner/runners/2.317.0/_diag/Worker_20240812-015530-utc.log'

Should I fork your project again to my GitHub and then run the workflow?

**Comment by homuler** [comment]
See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by lvxixi4ever** [comment]
> See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

The issue has been resolved, thanks!
