### ISSUE TITLE
Running examples on MacOS

### ISSUE THREAD

**Issue by SergeyAME** [homuler/MediaPipeUnityPlugin#22]
Hello. I understand, that currently is no support for Mac OS, but i try to implement it. 
First of all i modified Makefile & BUILD to build libmediapipe_c.dylib instead of libmediapipe_c.so. Now library is loaded, but i'm stuck on next error, while trying to open any model in scene DesktopCPU:

> MediaPipeException: INTERNAL: Graph has errors: 
Calculator::Open() for node "TfLiteInferenceCalculator" failed: ; Failed to load model from path._google_mediapipe/mediapipe/calculators/tflite/tflite_inference_calculator.cc:814) 
Mediapipe.Status.AssertOk () (at Assets/MediaPipe/SDK/Scripts/Framework/Port/Status.cs:40)
SceneDirector+<RunGraph>d__19.MoveNext () (at Assets/MediaPipe/Examples/Scripts/SceneDirector.cs:167)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:197)

**Comment by homuler** [comment]
Thank you for trying this on MacOS!

I have not tried it yet so I'm not sure, but I think it is necessary to build `resource_util_unity.cc` at least.
Currently, `resource_util_unity.cc` is not built for Mac OS, so please delete the below line ...
https://github.com/homuler/MediaPipeUnityPlugin/blob/master/C/third_party/mediapipe_model_path.diff#L26
and update `mediapipe_model_path.diff`.

If you're not in a hurry, I'll update it by myself a bit later.

**Comment by SergeyAME** [comment]
I'm doing something wrong.  I changed the file mediapipe_model_path.diff by adding "-" sign at line 26. (look at the attachment). But when i try to build libs, i get next error:

> external/com_google_mediapipe/mediapipe/util/resource_util_unity.cc:1:10: fatal error: 'mediapipe/util/resource_manager.h' file not found

[mediapipe_model_path.diff.zip](https://github.com/homuler/MediaPipeUnityPlugin/files/5589186/mediapipe_model_path.diff.zip)

p.s. thx for help. I wanna do it as faster as possible, to proceed to working with MediaPipe in our project. Of course i will do PR if everything goes well :)

**Comment by homuler** [comment]
I updated the patch file at the latest commit (https://github.com/homuler/MediaPipeUnityPlugin/commit/a71e613a049db0fcb1abb198b0c5e3758ee1095d).
Will you try again, please?

**Comment by SergeyAME** [comment]
Still the same error 
>external/com_google_mediapipe/mediapipe/util/resource_util_unity.cc:1:10: fatal error: 'mediapipe/util/resource_manager.h' file not found

More over, i can't do "make cpu". It produce same error now. 
I'm try to do "make clean" before "make cpu" but it doesn't help.

The version I'm trying to build differs only in this commit from the master: https://github.com/SergeyAME/MediaPipeUnityPlugin/commit/df13cf239ab81c4da662765717e6626fefb034d8

**Comment by homuler** [comment]
I'm sorry, I forgot to remove some lines.
Will you try with this file?
https://github.com/homuler/MediaPipeUnityPlugin/blob/feature/build-for-macos/C/third_party/mediapipe_model_path.diff

**Comment by SergeyAME** [comment]
It's start building now. Thx! 
Further I ran into an error in scene DesktopCPU:
>Input color array length needs to match width * height, but 256 != 640 * 480
UnityEngine.WebCamTexture:GetPixels32(Color32[])
WebCamScreenController:GetPixels32() (at Assets/MediaPipe/Examples/Scripts/WebCamScreenController.cs:55)
<RunGraph>d__18:MoveNext() (at Assets/MediaPipe/Examples/Scripts/SceneDirector.cs:160)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

I fix it with that commit: https://github.com/SergeyAME/MediaPipeUnityPlugin/commit/3ca707272bc7502e1a4406acc95c881768318259

Now i don't have any errors in log, but my screen looks like that:
![image](https://user-images.githubusercontent.com/74453846/100106696-eb633500-2e79-11eb-9ab4-97127f21c550.png)

**Comment by homuler** [comment]
The image is only got from WebCamera and applied to the Texter2D.
https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Assets/MediaPipe/Examples/Scripts/FaceDetection/FaceDetectionGraph.cs#L28

So the Texture2D might not be initialized correctly or `pixelData` length be wrong.

> Input color array length needs to match width * height, but 256 != 640 * 480

I'm not sure but the camera resolution may be wrong. How about changing `DefaultHeight` and `DefaultWidth` ?
https://github.com/homuler/MediaPipeUnityPlugin/blob/master/Assets/MediaPipe/Examples/Scripts/WebCamScreenController.cs#L5

**Comment by SergeyAME** [comment]
I wanna post quick update. You right. That was problem with Texture2D resolution. In Editor on MacOS i mess with 2 problems:
1) Some time, after WebCamTexture start playing, it return width and height 16x16 at that line: https://github.com/homuler/MediaPipeUnityPlugin/blob/b65fd5a77910fe999823399c220ca5dc460f578e/Assets/MediaPipe/Examples/Scripts/WebCamScreenController.cs#L32
I just use DefaultWidth and DefaultHeight instead of webCamTexture.width, webCamTexture.height
2) By default, in that line 
https://github.com/homuler/MediaPipeUnityPlugin/blob/b65fd5a77910fe999823399c220ca5dc460f578e/Assets/MediaPipe/Examples/Scripts/WebCamScreenController.cs#L32
we are creating WebCamTexture with resolution Default**Height** = **640** & Default**Width** = **480**, but in Editor on MacOS engine return WebCamTexture with Height = 480 and Width = 640. This leads to behavior as in the screenshot above. Quick workaround: just change swap Width & Height value in Editor.

I will continue further, trying to build a project for iOS.

**Comment by SergeyAME** [comment]
@homuler just a friendly reminder. That pull request https://github.com/homuler/MediaPipeUnityPlugin/pull/25 was to merge code in your branch. Not in master. So master still can't be build on OSX.

**Comment by homuler** [comment]
I'm sorry that I have not tested on macOS yet, but will you try running `make cpu`, please?

**Comment by SergeyAME** [comment]
Of course. `make cpu` works like it work before. I'm able to build library, but it didn't work in player. I have got "DllNotFoundException: mediapipe_c" error.

**Comment by SergeyAME** [comment]
I noticed that for some reason information about the required command `make mac_cpu` was missing in the final version of the ReadMe.md. Created a request to fix the documentation: https://github.com/homuler/MediaPipeUnityPlugin/pull/28

**Comment by homuler** [comment]
Thank you. I fixed at https://github.com/homuler/MediaPipeUnityPlugin/commit/b24e3eb93d17e3c49e6523e2064503cbbbf3a029

Now you can build libraries by running `make cpu`.

**Comment by homuler** [comment]
> I will continue further, trying to build a project for iOS.

iOS is supported now.

**Comment by SergeyAME** [comment]
What a great news! Thanks, for your work!
